package dev.brikk.chill.quarantine.generator.buildtime

import dev.brikk.chill.policy.ChillPolicyLoader
import dev.brikk.chill.quarantine.generator.jarfile.JarAllowancesGenerator
import java.io.File
import java.security.MessageDigest

/**
 * Writes a named library policy (`<name>.ctena`) from a [JarAllowancesGenerator] plus optional
 * hand-written lines, with a provenance header naming the scanned jars and their digests.
 *
 * This is the one place policies for third-party libraries are produced: the defaults shipped in
 * the chill jars are written by this at build time, and consumers regenerate against their own
 * library versions with the same writer to produce an override file (see [ChillPolicyLoader]).
 */
object LibraryPolicyWriter {

    class Written(val name: String, val file: File, val generatedLines: Int, val supportLines: Int)

    /**
     * @param outputRoot resources root; the file lands at `META-INF/chill/policy/<name>.ctena`
     * @param supportLines hand-written allowances appended after the generated ones
     */
    fun write(
        name: String,
        generator: JarAllowancesGenerator,
        outputRoot: File,
        supportLines: Collection<String> = emptyList(),
        supportDescription: String = "hand-written support allowances",
    ): Written {
        val generated = generator.generatePolicy()
        val file = File(outputRoot, "${ChillPolicyLoader.POLICY_RESOURCE_ROOT}/$name.${ChillPolicyLoader.POLICY_FILE_EXTENSION}")
        file.parentFile.mkdirs()
        file.bufferedWriter().use { out ->
            out.appendLine("# chill policy: $name")
            out.appendLine("# generated by ${LibraryPolicyWriter::class.java.name}; do not edit, regenerate")
            out.appendLine("# scan mode: ${generator.scanMode}")
            generator.jarFiles.map(::File).forEach { jar ->
                out.appendLine("# source: ${jar.name} sha256=${sha256(jar)}")
            }
            out.appendLine("# generated lines: ${generated.size}")
            generated.forEach { out.appendLine(it) }
            if (supportLines.isNotEmpty()) {
                out.appendLine("#")
                out.appendLine("# $supportDescription (${supportLines.size} lines)")
                supportLines.sorted().forEach { out.appendLine(it) }
            }
        }
        return Written(name, file, generated.size, supportLines.size)
    }

    private fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().use { input ->
            val buffer = ByteArray(64 * 1024)
            while (true) {
                val read = input.read(buffer)
                if (read < 0) break
                digest.update(buffer, 0, read)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
}
