package dev.brikk.chill.opensearch

import dev.brikk.chill.policy.ALL_PACKAGE_ACCESS_TYPES
import dev.brikk.chill.policy.AccessTypes
import dev.brikk.chill.policy.PolicyAllowance
import dev.brikk.chill.policy.toPolicy
import dev.brikk.chill.quarantine.Quarantine
import dev.brikk.chill.quarantine.generator.jarfile.JarAllowancesGenerator
import dev.brikk.chill.quarantine.generator.jarfile.ScanMode
import dev.brikk.chill.serialize.Chill
import kotlinx.serialization.KSerializer
import java.io.File

/**
 * The shared chill configuration for OpenSearch scripting, used identically on the freezing
 * client and the verifying server plugin.
 */
object ChillOpenSearch {
    /** Script language name registered by the plugin. */
    const val LANGUAGE = ChillScript.LANG

    private val receiverClassName = ChillSearchScript::class.java.name

    /**
     * Allowances for the script receiver: instance methods and property reads, plus ref-only of
     * Class/reflect.Type so reified helpers can pass `T::class.java` without enabling reflection.
     * Static methods included: Kotlin default-argument calls compile to synthetic static
     * `name$default` bridges on the receiver class.
     */
    val receiverPolicies: Set<String> = listOf(
        PolicyAllowance.ClassLevel.ClassAccess(receiverClassName, setOf(AccessTypes.ref_Class_Instance)),
        PolicyAllowance.ClassLevel.ClassMethodAccess(receiverClassName, "*", "*", setOf(AccessTypes.call_Class_Instance_Method, AccessTypes.call_Class_Static_Method)),
        PolicyAllowance.ClassLevel.ClassPropertyAccess(receiverClassName, "*", "*", setOf(AccessTypes.read_Class_Instance_Property)),
        PolicyAllowance.ClassLevel.ClassAccess(java.lang.reflect.Type::class.java.name, setOf(AccessTypes.ref_Class_Instance)),
        PolicyAllowance.ClassLevel.ClassAccess(Class::class.java.name, setOf(AccessTypes.ref_Class)),
    ).toPolicy().toSet()

    /**
     * Pure-computation kotlin-stdlib packages allowed wholesale for script bodies. The generated
     * stdlib policy black-lists a whole facade class when any single member fails verification,
     * which knocks out everyday helpers (map/filter/toRegex/...); these packages contain no IO,
     * reflection, or process surface.
     */
    val scriptKotlinPackagePolicies: Set<String> = listOf(
        "kotlin.collections",
        "kotlin.text",
        "kotlin.sequences",
        "kotlin.ranges",
        "kotlin.comparisons",
    ).map { PolicyAllowance.PackageAccess(it, ALL_PACKAGE_ACCESS_TYPES, requireSealed = false) }
        .toPolicy().toSet()

    /**
     * kotlinx-serialization-core allowances, generated by scanning the runtime jar that ships
     * inside the plugin (same treatment as kotlin-stdlib; nothing hand-listed). The runtime is
     * pure computation - descriptors, encoders, decoders - with no IO/process/reflection-invoke
     * surface, so its public API is generated in full.
     */
    val kotlinxSerializationPolicies: Set<String> by lazy {
        val jar = File(KSerializer::class.java.protectionDomain.codeSource.location.toURI())
        JarAllowancesGenerator(
            jarFiles = listOf(jar.path),
            scanMode = ScanMode.ALL,
            preFilterPackageWhiteList = listOf("kotlinx.serialization"),
            postFilterPackageWhiteList = listOf("kotlinx.serialization"),
            postFilterPackageBlackList = emptyList(),
            postFilterClassBlackList = emptySet(),
            verifier = Quarantine(Quarantine.painlessPlusKotlinBootstrapPolicy),
            useClassLoader = KSerializer::class.java.classLoader,
        ).generatePolicy().toSet()
    }

    /**
     * The compiler-generated `$serializer` of a shipped `@Serializable` class also references a
     * little kotlin reflection-lite plumbing (name metadata only, works without kotlin-reflect,
     * cannot invoke anything).
     */
    val serializationSupportPolicies: Set<String> = (
        listOf(
            PolicyAllowance.ClassLevel.ClassAccess("kotlin.jvm.internal.Reflection", setOf(AccessTypes.ref_Class_Static)),
            PolicyAllowance.ClassLevel.ClassMethodAccess("kotlin.jvm.internal.Reflection", "*", "*", setOf(AccessTypes.call_Class_Static_Method)),
            PolicyAllowance.ClassLevel.ClassAccess("kotlin.reflect.KClass", setOf(AccessTypes.ref_Class, AccessTypes.ref_Class_Instance)),
            PolicyAllowance.ClassLevel.ClassAccess(java.time.ZonedDateTime::class.java.name, setOf(AccessTypes.ref_Class, AccessTypes.ref_Class_Instance)),
        ) +
            // kotlin annotations stamped onto generated serializer/companion classes: pure
            // annotation type references, zero capability
            listOf(
                "kotlin.jvm.JvmStatic",
                "kotlin.jvm.JvmField",
                "kotlin.Deprecated",
                "kotlin.DeprecationLevel",
                "kotlin.ReplaceWith",
            ).map { PolicyAllowance.ClassLevel.ClassAccess(it, setOf(AccessTypes.ref_Class)) } +
            // kotlinx generates lazily-cached descriptors: enum constant reads only
            listOf(
                PolicyAllowance.ClassLevel.ClassAccess("kotlin.LazyThreadSafetyMode", setOf(AccessTypes.ref_Class, AccessTypes.ref_Class_Instance, AccessTypes.ref_Class_Static)),
            ) +
            listOf("SYNCHRONIZED", "PUBLICATION", "NONE").map {
                PolicyAllowance.ClassLevel.ClassFieldAccess("kotlin.LazyThreadSafetyMode", it, "Lkotlin/LazyThreadSafetyMode;", setOf(AccessTypes.read_Class_Static_Field))
            }
        ).toPolicy().toSet()

    val quarantine: Quarantine by lazy {
        Quarantine(
            Quarantine.painlessPlusKotlinFullPolicy +
                receiverPolicies +
                scriptKotlinPackagePolicies +
                kotlinxSerializationPolicies +
                serializationSupportPolicies,
        )
    }

    val chill: Chill by lazy { Chill(quarantine) }

    // ---- freeze -----------------------------------------------------------------------------

    private fun freeze(slots: List<ChillSlot>, lambda: Any): String {
        require(slots.map { it.kind }.toSet().size == slots.size) { "Each slot kind may be bound at most once: ${slots.map { it.kind }}" }
        val shipClasses = slots.flatMap { shipSet(it.boundClass) }.distinct()
        return chill.serializeFunctionToBase64(
            lambdaReceiver = ChillSearchScript::class,
            lambdaReturnType = Any::class,
            slots = slots.map { Chill.SlotDescriptor(it.kind, it.boundClass.name) },
            shipClasses = shipClasses,
            lambda = lambda,
        )
    }

    /** A bound class ships with its nested classes: kotlinx generates `Companion` and `$serializer`. */
    private fun shipSet(clazz: Class<*>): List<Class<*>> {
        val result = LinkedHashSet<Class<*>>()
        fun visit(c: Class<*>) {
            if (result.add(c)) c.declaredClasses.forEach { visit(it) }
        }
        visit(clazz)
        return result.toList()
    }

    // ---- script(): one name, slot types pick the result kind ---------------------------------
    // paramOf  -> ChillScript (ready), paramType -> ChillScriptTemplate (reusable);
    // canonical slot order: params, doc, source.

    fun script(block: ChillSearchScript.() -> Any?): ChillScript =
        ChillScript(freeze(emptyList(), block), emptyMap())

    fun <P : Any> script(p: ParamValueSlot<P>, block: ChillSearchScript.(P) -> Any?): ChillScript =
        ChillScript(freeze(listOf(p), block), ParamsCodec.encodeToMap(p.serializer, p.value))

    fun <P : Any> script(p: ParamTypeSlot<P>, block: ChillSearchScript.(P) -> Any?): ChillScriptTemplate<P> =
        ChillScriptTemplate(freeze(listOf(p), block), p.serializer)

    fun <D : Any> script(d: DocSlot<D>, block: ChillSearchScript.(D) -> Any?): ChillScript =
        ChillScript(freeze(listOf(d), block), emptyMap())

    fun <S : Any> script(s: SourceSlot<S>, block: ChillSearchScript.(S) -> Any?): ChillScript =
        ChillScript(freeze(listOf(s), block), emptyMap())

    fun <P : Any, D : Any> script(p: ParamValueSlot<P>, d: DocSlot<D>, block: ChillSearchScript.(P, D) -> Any?): ChillScript =
        ChillScript(freeze(listOf(p, d), block), ParamsCodec.encodeToMap(p.serializer, p.value))

    fun <P : Any, D : Any> script(p: ParamTypeSlot<P>, d: DocSlot<D>, block: ChillSearchScript.(P, D) -> Any?): ChillScriptTemplate<P> =
        ChillScriptTemplate(freeze(listOf(p, d), block), p.serializer)

    fun <P : Any, S : Any> script(p: ParamValueSlot<P>, s: SourceSlot<S>, block: ChillSearchScript.(P, S) -> Any?): ChillScript =
        ChillScript(freeze(listOf(p, s), block), ParamsCodec.encodeToMap(p.serializer, p.value))

    fun <P : Any, S : Any> script(p: ParamTypeSlot<P>, s: SourceSlot<S>, block: ChillSearchScript.(P, S) -> Any?): ChillScriptTemplate<P> =
        ChillScriptTemplate(freeze(listOf(p, s), block), p.serializer)

    fun <D : Any, S : Any> script(d: DocSlot<D>, s: SourceSlot<S>, block: ChillSearchScript.(D, S) -> Any?): ChillScript =
        ChillScript(freeze(listOf(d, s), block), emptyMap())

    fun <P : Any, D : Any, S : Any> script(p: ParamValueSlot<P>, d: DocSlot<D>, s: SourceSlot<S>, block: ChillSearchScript.(P, D, S) -> Any?): ChillScript =
        ChillScript(freeze(listOf(p, d, s), block), ParamsCodec.encodeToMap(p.serializer, p.value))

    fun <P : Any, D : Any, S : Any> script(p: ParamTypeSlot<P>, d: DocSlot<D>, s: SourceSlot<S>, block: ChillSearchScript.(P, D, S) -> Any?): ChillScriptTemplate<P> =
        ChillScriptTemplate(freeze(listOf(p, d, s), block), p.serializer)
}
